"use strict";

module.exports = Object.freeze({
  runtimeInfo: "biodesign:runtime:info",
  betaUpdateCheck: "biodesign:updates:beta-check",
  betaUpdateStatus: "biodesign:updates:beta-status",
  projectOpen: "biodesign:project:open",
  projectClose: "biodesign:project:close",
  projectStatus: "biodesign:project:status",
  filesList: "biodesign:files:list",
  filesStat: "biodesign:files:stat",
  filesExists: "biodesign:files:exists",
  filesReadText: "biodesign:files:read-text",
  filesReadBinary: "biodesign:files:read-binary",
  filesWriteText: "biodesign:files:write-text",
  filesWriteBinary: "biodesign:files:write-binary",
  filesMkdir: "biodesign:files:mkdir",
  filesRemove: "biodesign:files:remove",
  filesTree: "biodesign:files:tree",
  knowledgeInitialize: "biodesign:knowledge:initialize",
  knowledgeStatus: "biodesign:knowledge:status",
  knowledgeUpdate: "biodesign:knowledge:update",
  knowledgeEmbed: "biodesign:knowledge:embed",
  knowledgeSearch: "biodesign:knowledge:search",
  knowledgeDocument: "biodesign:knowledge:document",
  knowledgeProgress: "biodesign:knowledge:progress",
  jobsStart: "biodesign:jobs:start",
  jobsStatus: "biodesign:jobs:status",
  jobsList: "biodesign:jobs:list",
  jobsCancel: "biodesign:jobs:cancel",
  executionList: "biodesign:execution:list",
  executionRun: "biodesign:execution:run",
});
