async function runAgentScenarios() {
  document.getElementById("loginPanel").hidden = true;
  document.getElementById("loginPanel").classList.add("is-hidden");
  const shell = document.getElementById("appShell"); shell.hidden = false; shell.classList.remove("is-hidden");
  document.getElementById("sideChatExamples").hidden = true;
  document.getElementById("sideChatContextChips").textContent = "Entire Project";
  document.getElementById("projectContext").value = "Compare evidence and plan the next analysis.";
  const legacy = normalizeStoredAnalysisPanel({ id: "legacy", instruction: "Previously reviewed evidence", frozen: true, collapsed: true, recommendation: { ...createDefaultRecommendation(), currentInterpretation: "Previous result", updatedAt: "2026-09-01T12:00:00.000Z" } });
  analysisPanels = [legacy]; renderAnalysisPanels();
  check(legacy.messages.length === 2 && !legacy.frozen && legacy.collapsed, "Legacy result becomes editable chat history without losing its collapse state");
  const savedResult = currentRecommendation;
  addAnalysisPanelButton.click(); const first = analysisPanels[1];
  draft(first, "Review candidate evidence");
  setting(first, "selectedModel", sideChatModelSelect.options[1].value);
  setting(first, "selectedPermission", "workspace_write");
  const files = new DataTransfer(); files.items.add(new File(["a,b"], "results.csv", { type: "text/csv" })); files.items.add(new File(["image"], "figure.png", { type: "image/png" }));
  const picker = card(first).querySelector('[data-agent-attachments="file"]'); picker.files = files.files; picker.dispatchEvent(new Event("change", { bubbles: true }));
  check(first.pendingAttachments.length === 2 && card(first).textContent.includes("figure.png"), "File and image selections produce removable chips");
  click(first, "remove-attachment");
  check(first.pendingAttachments.length === 1 && first.pendingAttachments[0].name === "figure.png", "Remove affects only the selected attachment");
  click(first, "new-chat"); const second = analysisPanels[2]; draft(second, "An independent second task");
  check(analysisPanels.every(chat => card(chat).querySelector('[data-analysis-action="new-chat"]') && card(chat).querySelector('[data-analysis-action="delete"]')), "Every expanded or collapsed task has new-chat and delete controls");
  const panelGap = card(second).getBoundingClientRect().top - card(first).getBoundingClientRect().bottom;
  check(panelGap >= 24 && !document.querySelector(".analysis-workspace-panel").classList.contains("workbench-panel") && card(first).classList.contains("workbench-panel"), "Tasks are separate panels with a visible page-background gap");
  check(first.instruction === "Review candidate evidence" && !first.collapsed && first.pendingAttachments.length === 1 && second.selectedPermission === "read_only", "Adding a chat preserves drafts, attachments, selections and expanded cards");
  check(currentRecommendation === savedResult && sideChatModelSelect.value === "default", "New tasks and Agent model changes leave the current result and Side Chat selection alone");
  click(first, "toggle");
  check(first.collapsed && !second.collapsed && card(first).querySelector(".agent-chat-summary").textContent.includes("Review candidate"), "Independent collapse keeps a meaningful clickable summary");
  card(first).querySelector(".agent-chat-summary").click();
  const focused = draft(second, "Continue drafting while the first task runs"); focused.focus(); focused.setSelectionRange(4, 9); renderAnalysisPanels();
  check(document.activeElement.value === second.instruction && document.activeElement.selectionStart === 4, "Progress renders preserve composer focus and selection");
  let release; requestGate = new Promise(resolve => { release = resolve; });
  card(first).querySelector("form").requestSubmit(); await tick();
  check(first.taskStatus === "running" && first.messages.length === 1 && card(second).querySelector('[type="submit"]').disabled, "Submit creates a user turn and preserves the existing single-run guard");
  deleteAnalysisPanel(first.id);
  check(findAnalysisPanel(first.id) === first && card(first).querySelector('[data-analysis-action="delete"]').disabled, "Running tasks cannot be deleted or detached from their execution");
  click(legacy, "new-chat"); const temporary = analysisPanels[1];
  check(temporary !== first && analysisPanels[2] === first, "A card's new-chat action inserts immediately below that card");
  click(temporary, "delete");
  check(!findAnalysisPanel(temporary.id) && activeAgentPanelId === first.id && first.taskStatus === "running", "Deleting a different task leaves the current run intact");
  check(!requests[0].model && !requests[0].permission && !requests[0].attachments && requests[0].messages[0].content === "Review candidate evidence", "UI selections and files do not alter the execution payload");
  check(first.messages[0].requestedModel === sideChatModelSelect.options[1].value && first.messages[0].permission === "workspace_write" && first.messages[0].attachments[0].name === "figure.png", "Submitted turn captures requested model, permission and attachment metadata");
  draft(first, "A follow-up draft"); setting(first, "selectedPermission", "full_access");
  click(first, "toggle"); await tick(); card(first).querySelector(".agent-chat-summary").click(); await tick();
  check(card(first).textContent.includes("Streaming task response"), "Streaming preview survives independent collapse and expand");
  click(first, "toggle"); release(); await tick(); requestGate = null;
  check(first.taskStatus === "completed" && first.collapsed && first.instruction === "A follow-up draft" && first.messages[0].permission === "workspace_write", "Completion respects collapse and preserves the next draft without changing submitted metadata");
  card(first).querySelector(".agent-chat-summary").click();
  check(card(first).querySelector("pre code") && card(first).querySelector("ol") && card(first).querySelector("ul"), "Agent turns reuse formatted Markdown for lists, code, headings and file references");
  click(first, "review"); click(first, "export"); click(first, "copy"); await tick();
  check(first.recommendation.reviewed && exports[0] === first.recommendation && copies[0].includes("Evidence review"), "Review, export and copy remain connected to the real recommendation state");
  const committed = first.recommendation;
  requestFailure = Object.assign(new Error("Interrupted"), { code: "STREAM_INTERRUPTED" });
  await runAgentInstruction(first.id); requestFailure = null;
  check(first.taskStatus === "failed" && first.messages.length === 4 && first.recommendation === committed, "An interrupted follow-up stays in history and does not replace the committed result");
  draft(first, "Retry the task"); await runAgentInstruction(first.id);
  check(first.messages.length === 6 && first.taskStatus === "completed" && second.messages.length === 0, "A follow-up appends to its own conversation and recovers after failure");
  const stored = JSON.parse(sessionStorage.getItem(ANALYSIS_PANELS_STORAGE_KEY));
  const restored = stored.map(normalizeStoredAnalysisPanel);
  check(restored[1].messages.length === 6 && !restored[0].frozen && !restored[1].frozen && restored[2].instruction === second.instruction && restored.every(chat => chat.pendingAttachments.length === 0), "Session reload preserves independent chats and omits pending file objects");
  check(!JSON.stringify(stored).includes('"file":') && !JSON.stringify(stored).includes('"pendingAttachments":'), "No attachment bytes or File objects enter session storage");
  const interrupted = normalizeStoredAnalysisPanel({ ...stored[1], taskStatus: "running", status: "Busy", statusKey: "agentReviewing" });
  check(interrupted.taskStatus === "waiting" && !interrupted.status && !interrupted.statusKey, "Reloading an interrupted task does not leave it stuck running");
  for (let i = 0; i < 30; i++) first.messages.push({ role: i % 2 ? "assistant" : "user", content: `History item ${i}\n\nA sufficiently long paragraph to exercise internal conversation scrolling.` });
  renderAnalysisPanels();
  const history = card(first).querySelector(".agent-conversation"); history.scrollTop = 30; renderAnalysisPanels();
  check(history.scrollHeight > history.clientHeight && history.scrollTop === 30 && card(first).getBoundingClientRect().height === 660, "Long history stays within a bounded card and preserves the reader scroll position");
  for (let i = 0; i < 3; i++) addAnalysisPanelButton.click();
  await tick();
  window.scrollTo(0, 1700); await tick();
  const side = document.querySelector(".side-column").getBoundingClientRect();
  check(side.top >= 15 && side.top <= 17 && side.bottom <= innerHeight, "Side Chat remains sticky in the viewport beside lower Agent tasks");
  const preservedChats = [...analysisPanels];
  const preservedResult = JSON.stringify(currentRecommendation);
  const preservedSecond = JSON.stringify(second);
  click(first, "delete");
  check(!findAnalysisPanel(first.id) && !card(first) && JSON.stringify(second) === preservedSecond, "Deleting a chosen task preserves every other task's local state");
  check(JSON.stringify(currentRecommendation) === preservedResult && !loadAnalysisPanels().some(chat => chat.id === first.id), "Deletion survives reload without changing the last committed recommendation");
  for (const chat of [...analysisPanels]) click(chat, "delete");
  check(!analysisPanels.length && !loadAnalysisPanels().length && analysisPanelStack.textContent.includes(t("agentNoTasks")), "Deleting all tasks leaves a persistent empty state instead of resurrecting history");
  addAnalysisPanelButton.click();
  check(analysisPanels.length === 1 && !analysisPanels[0].messages.length, "A fresh chat can be created after deleting the last task");
  analysisPanels = preservedChats; saveAnalysisPanels();
  // Leave a useful desktop preview with real rendered results and a collapsed task.
  analysisPanels.slice(3).forEach(chat => { chat.collapsed = true; });
  first.messages = first.messages.slice(0, 6); renderAnalysisPanels();
  card(first).querySelector(".agent-conversation").scrollTop = 0;
  window.scrollTo(0, 0);
}

async function checkResponsive(width) {
  await tick(); window.scrollTo(0, 0);
  const first = analysisPanels[1];
  const composer = card(first).querySelector("form");
  check(composer.scrollWidth <= composer.clientWidth + 1, `Composer controls fit at ${width}px`);
  const actions = card(first).querySelector(".agent-task-actions");
  check(actions.scrollWidth <= actions.clientWidth + 1, `Task actions fit at ${width}px`);
  check(card(first).querySelector(".analysis-panel-header").getBoundingClientRect().height < 150 && card(first).querySelector(".agent-conversation").clientHeight >= 150, `Task header stays compact and leaves room for conversation at ${width}px`);
  check(document.documentElement.scrollWidth <= innerWidth + 1, `Page has no horizontal overflow at ${width}px`);
  if (width <= 1280) check(getComputedStyle(document.querySelector(".side-column")).position === "static", `Existing responsive Side Chat stacking retained at ${width}px`);
  else check(getComputedStyle(document.querySelector(".workbench-grid")).gridTemplateColumns.split(" ").length === 3, `Three desktop columns retained at ${width}px`);
}
